# Generated by Django 4.2.2 on 2023-06-17 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.IntegerField()),
                ('dv', models.CharField(max_length=1)),
                ('primerApellido', models.CharField(max_length=100)),
                ('segundoApellido', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Donantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.IntegerField()),
                ('dv', models.CharField(max_length=1)),
                ('primerApellido', models.CharField(max_length=100)),
                ('segundoApellido', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Mascotas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especie', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Regiones',
            fields=[
                ('cutReg', models.IntegerField(db_column='cut_reg', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='nombre', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=255)),
                ('clienteId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.clientes')),
            ],
        ),
        migrations.CreateModel(
            name='Provincias',
            fields=[
                ('cutProv', models.IntegerField(db_column='cut_prov', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.regiones')),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.IntegerField()),
                ('imagen', models.CharField(max_length=255)),
                ('stock', models.IntegerField()),
                ('categoria_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.categorias')),
                ('mascotaId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.mascotas')),
            ],
        ),
        migrations.CreateModel(
            name='Comunas',
            fields=[
                ('cutCom', models.IntegerField(db_column='cut_com', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='nombre', max_length=50)),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.provincias')),
                ('regionProv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.regiones')),
            ],
        ),
        migrations.AddField(
            model_name='clientes',
            name='comId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.comunas'),
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valorTotal', models.IntegerField(default=0)),
                ('clienteId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.clientes')),
            ],
        ),
    ]
